//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace umeAPI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int idMessage { get; set; }
        public int idUser { get; set; }
        public int toUserId { get; set; }
        public string status { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<System.DateTime> createOn { get; set; }
        public Nullable<bool> IisGim { get; set; }
        public Nullable<System.DateTime> viewOn { get; set; }
    }
}
