//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace umeAPI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserNotification
    {
        public int idNotification { get; set; }
        public Nullable<bool> isRead { get; set; }
        public string content { get; set; }
        public Nullable<System.DateTime> creataOn { get; set; }
        public Nullable<System.DateTime> readOn { get; set; }
        public int idUser { get; set; }
        public int idPerson { get; set; }
    }
}
